// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqrmKMoxyu3_ztrm7wi98bRNVeGW9UUGM',
    appId: '1:553791720373:web:022a99fc92bc6a83e8a7fc',
    messagingSenderId: '553791720373',
    projectId: 'dicoding-chatting-bbc40',
    authDomain: 'dicoding-chatting-bbc40.firebaseapp.com',
    storageBucket: 'dicoding-chatting-bbc40.appspot.com',
    measurementId: 'G-DCVJRJBME2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKLZD7UQERLAw3oHstgnSh8x4VapL5sh0',
    appId: '1:553791720373:android:c9d5f75296b83fe6e8a7fc',
    messagingSenderId: '553791720373',
    projectId: 'dicoding-chatting-bbc40',
    storageBucket: 'dicoding-chatting-bbc40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPwiycjgDdNtrR87UEG-OpGcJaB9EKj5g',
    appId: '1:553791720373:ios:dc6548db311929f1e8a7fc',
    messagingSenderId: '553791720373',
    projectId: 'dicoding-chatting-bbc40',
    storageBucket: 'dicoding-chatting-bbc40.appspot.com',
    iosClientId: '553791720373-tmgmmsnqvct3qeke9ukne1g0gk8576dm.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.dicodingChatting',
  );
}
